[package]
name = "p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = "0.46.1"
tokio = { version = "1.19.2", features = ["full"] }
log = "^0.4"
log4rs = "^1.3"
serde_yaml = "0.9.34+deprecated"
chrono = "^0.4"
